= LiquiDoc

LiquiDoc is a system for true single-sourcing of content and data in flat files.
It is especially suited for projects various required output formats, but it's ideal for any project with complex input data that needs to be used in documentation or user interfaces.
The command-line utility engages templating systems to parse complex data into rich text output.

Sources can be flat files formatted in formats such as XML (eXtensible Markup Language), JSON (JavaScript Object Notation), CSV (comma-separated values), and our preferred human-editable format: YAML (Who knows).
LiquiDoc can also parse unconventionally formatted files using regular expression matching.

Output can (or will) be pretty much any flat file, including semi-structured data like JSON and XML, as well as rich text/multimedia formats like HTML, PDF, slide decks, and more.

== Purpose

LiquiDoc is for building documentation from semi-structured or mixed data formats.
It parses source data from flat files into secondary markup languages, usually for output as rich text media, or simply as an alternate semi-structured format.
Unlike tools that are mere converters, LiquiDoc can be configured to perform multiple operations at once for generating content from multiple data source files, each output in various formats based on distinct templates.

LiquiDoc is a build tool.
It can be integrated into build- and package-management systems.
The tool currently provides for very basic configuration of build jobs, with extensibility coming soon, including a secondary publish function for generating link:http://asciidoctor.org/[Asciidoctor] output from data-driven AsciiDoc files as well as integrated Jekyll static site build/serve functionality.

== Installation

[NOTE]
Your system must be running Ruby 2.3 or later.
Linux and MacOS users should be okay.
See https://www.ruby-lang.org/en/downloads/[Ruby downloads] if you're on Windows.

. Create a file called `Gemfile` in your project's root directory.

. Populate the file with LiquiDoc dependencies.
+
.A LiquiDoc project Gemfile
[source,ruby]
----
source 'https://rubygems.org'

gem 'json'
gem 'liquid'
gem 'asciidoctor'
gem 'logger'
gem 'crack'
gem 'liquidoc'
----
+
[TIP]
This file is included in the link:https://github.com/briandominick/liquidoc-boilerplate[LiquiDoc boilerplate files].

. Run `bundle install` to prepare dependencies.

== Usage

LiquiDoc provides a Ruby command-line tool for processing source files into new text files based on templates you define.
These definitions can be command-line options, or they can be instructed by preset configurations you define in separate configuration files.

[TIP]
.Quickstart
If you want to test the tool out with dummy data and templates, clone link:https://github.com/briandominick/liquidoc-boilerplate[this boilerplate repo] and run the suggested commands.

Give LiquiDoc (1) any proper YAML, JSON, XML, or CSV (with header row) data file and (2) a template mapping any of the data to token variables with Liquid markup -- LiquiDoc returns STDOUT feedback or writes a new file (or multiple files) based on that template.

.Example -- Generate sample output from files established in a configuration
----
$ bundle exec liquidoc -c _configs/cfg-sample.yml --stdout
----

[TIP]
Repeat without the `--stdout` flag and you'll find the generated files in `_output/`.

.Example -- Generate output from files passed as CLI arguments
----
$ bundle exec liquidoc -d _data/data-sample.yml -t _templates/liquid/tpl-sample.asciidoc -o sample.adoc
----

[TIP]
Add `--verbose` to see the steps LiquiDoc is taking.

=== Configuration

The best way to use LiquiDoc is with a configuration file.
This not only makes the command line much easier to manage (requiring just a configuration file path argument), it also adds the ability to perform more complex builds.

Here is the basic structure of a valid config file:

[source,yaml]
.LiquiDoc config file for recognized format parsing
----
compile:
  data: source_data_file.json # <1>
  builds: # <2>
    - template: liquid_template.html # <3>
      output: _output/output_file.html # <4>
    - template: liquid_template.markdown # <3>
      output: _output/output_file.md # <4>
----

<1> If the *data* setting's value is a string, it must be the filename of a format automatically recognized by LiquiDoc: `.yml`, `.json`, `.xml`, or `.csv`.

<2> The *builds* section contains a list of procedures to perform on the data.
It can contain as many build procedures as you wish to carry out.
Thise one instructs two builds.

<3> The *template* setting should be a liquid-formatted file (see <<templating>> below).

<4> The *output* setting is a path and filename where you wish the output to be saved.
Can also be `stdout`.

[source,yaml]
.LiquiDoc config file for recognized format parsing
----
compile:
  data: # <1>
    file: source_data_file.json # <2>
    type: regex # <3>
    pattern: (?<kee>[A-Z0-9_]+)\s(?<valu>.*)\n # <4>
  builds: # <5>
    - template: liquid_template.html
      output: _output/output_file.html
    - template: liquid_template.markdown
      output: _output/output_file.md
----

<1> In this format, the *data* setting contains several other settings.

<2> The *file* setting accepts _any_ text file, no matter the file extension or data formatting within the file.
This field is required.

<3> The *type* field can be set to `regex` if you will be using a regular expression pattern to extract data from lines in the file.
It can also be set to `yml`, `json`, `xml`, or `csv` if your file is in one of these formats but uses a nonstandard extension.

<4> If your type is `regex`, you must supply a regular expression pattern.
This pattern will be applied to each line of the file, scanning for matches to turn into key-value pairs.
Your pattern must contain at least two groups, denoted with unescaped `(` and `)` markers containing a “named group”, denoted with `?<string>`, where `string` is the name for the variable name to assign to any content matching the pattern contained in the ret of the group (everuthing else between the unescaped parentheses.).

<5> The build section is the same in this configuration.

When you've established a configuration file, you can call it with the argument `-c`/`--config` on the command line.

=== Data Sources

Valid data sources come in a few different types.
There are the built-in data types (YAML, JSON, XML, CSV) vs free-form type (files processed using regular expressions, designated the `regex` data type).
There is also a divide between simple one-record-per-line data types (CSV and regex), which produce one record per line, vs nested data types that have far more complex structures.

=== Native Nested Data (YAML, JSON, XML)

The native nested formats are actually the most straightforward.

==== CSV Data

CSV-derived data will use the first row as key names for columnar data in the subsequent rows, as shown below.

.Example -- sample.csv showing header/key and value rows
[source,csv]
----
name,description,default,required
enabled,Whether project is active,,true
timeout,The duration of a session (in seconds),300,false
----

The above source data, parsed as a CSV file, will yield the following array.

.Example -- array derived from sample.csv, with values depicted
[source,ruby]
----
data[0].name #=> enabled
data[0].description #=> Whether project is active
data[0].default #=> nil
data[0].required #=> true
data[1].name #=> timeout
data[1].description #=> The duration of a session (in seconds)
data[1].default #=> 300
data[1].required #=> false
----

==== Free-form Data

Free-form data can only be parsed using regex patterns -- otherwise, it has no idea what to consider data.

Any file organized with one-record per line may be consumed and parsed by LiquiDoc, provided you instruct the parser as to what variables to extract from where.
The parser will read each line individually, applying your regex pattern to extract data.

.Example -- sample.free free-form data source file
----
A_B A thing that *SnASFHE&"\|+1Dsaghf true
G_H Some text for &hdf 1t`F false
----

.Example -- regular expression with named groups for variable generation
[source,regex]
----
^(?<name>[A-Z_]+)\s(?<description>.*)\s(?<required>true|false)\n
----

.Example -- array derived from sample.free using above regex pattern
[source,ruby]
----
data[0].name #=> A_B
data[0].description #=> A thing that *SnASFHE&"\|+1Dsaghf
data[0].required #=> true
data[1].name #=> G_H
data[1].description #=> Some text for &hdf'" 1t`F
data[1].required #=> false
----

As you can see, free-form/regex parsing is more complicated than the other types.
Its use case is usually when you simply cannot control the form your source takes.

The regex type is also useful when the content of some fields would be burdensome to store in conventional semi-structured formats like those natively parsed by LiquiDoc.
This is the case for jumbled content that contains characters that require escaping, so you can keep source like that in the example above in a more pure form.

=== Templating

LiquiDoc will add the powers of Asciidoctor in a future release, enabling initial reformatting of complex source data _into_ AsciiDoc format using Liquid templates, followed by final publishing into rich formats such as PDF, HTML, and even slide presentations.

link:https://help.shopify.com/themes/liquid/basics[*Liquid*] is used for parsing complex variable data, typically for iterated output.
For instance, an array of glossary terms and definitions that needs to be looped over and pressed into a more publish-ready markup, such as Markdown, AsciiDoc, reStructuredText, LaTeX, or HTML.

Any valid Liquid-formatted template is accepted, in the form of a text with of any file extension.
For data sourced in CSV format or extracted through regex source parsing, all data is passed to the Liquid template parser as a variable called *data*, containing one or more rows (records) to be iterated through.
Data sourced in YAML, XML, or JSON may be passed as more complex structures with custom names determined in the file.

=== Output

After this parsing, files are written in any of the given output formats, or else just written to system as STDOUT (when you add the `--stdout` flag to your command or set `output: stdout` in your config file).
Liquid templates can be used to produce any flat-file format imaginable.
Just format valid syntax with your source data and Liquid template, then save with the proper extension, and you're all set.

== Contributing

Contributions are open and welcome.
This repo is maintained by Rocana's documentation manager, who taught himself basic Ruby scripting just to build LiquiDoc and related tooling.
Instructional pull requests are encouraged!

== License

LiquiDoc is provided by Rocana, Inc under the MIT License.
